anguage: generic

cache:
  directories:
    # General SwiftPM
    - .build
    # XCodebuild cache
    - Build

matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - gem install bundler
        - bundle install
        - npm install -g danger
      script:
        - swift package generate-xcodeproj
        - swift build
        - xcodebuild test -scheme DangerSwiftCoverage-Package -derivedDataPath Build/ -enableCodeCoverage YES | XCPRETTY_JSON_FILE_OUTPUT=result.json xcpretty -f `xcpretty-json-formatter`
        - DEBUG="*" swift run danger-swift ci
    - os: osx
      osx_image: xcode10.2
      install:
        - gem install bundler
        - bundle install
        - npm install -g danger
      script:
        - swift test --enable-code-coverage=true
        - DEBUG="*" swift run danger-swift ci --id spmCoverage --dangerfile SPMDangerfile.swift
